# -*- coding: utf-8 -*-
"""D3 assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TqCuzAA4Wju8QhC5sbLIqzx0OSSi7n9-
"""

!pip install boruta

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from boruta import BorutaPy
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.decomposition import PCA
from sklearn.feature_selection import SelectFromModel
from sklearn.preprocessing import label_binarize
from sklearn.metrics import roc_curve, auc
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score, classification_report, precision_recall_curve
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from imblearn.over_sampling import SMOTE
import xgboost as xgb
from xgboost import XGBClassifier
from sklearn.preprocessing import LabelEncoder

#===============================================================================
# Load Spectral Data
#===============================================================================
# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Define the Google Drive path to the rawASD data (adjust the file path as needed)
file_path = ('/content/drive/MyDrive/Spectral samples/ASD_raw_Dec2023_LA.csv')

#  Load the rawASD dataset
rawASD = pd.read_csv(file_path)

# Check the first few rows of the dataset to ensure it loaded correctly
print(rawASD.head())
print("Dataset dimensions: ", rawASD.shape)

#===============================================================================
# Plot All Spectra with Atmospheric Windows
#===============================================================================

# Plot all spectra (excluding first column which contains wavelength)
plt.figure(figsize=(10, 6))
for col in rawASD.columns[1:]:
    plt.plot(rawASD.iloc[:, 0], rawASD[col], linewidth=1)

plt.xlabel('Wavelength (nm)')
plt.ylabel('Sample Reflectance')
plt.title('Spectral Plot')
plt.show()

#===============================================================================
# Clean and Reformat Data for Analysis
#===============================================================================
# Convert the rawASD DataFrame (transposed)
input_data = rawASD.T # Transpose the DataFrame
input_data.columns = rawASD.iloc[:, 0]  # Set column names to first row
input_data.columns = ['wb_' + str(col) if isinstance(col, (int, float)) else 'wb_' + col for col in input_data.columns]

# Remove the first row (header) which is now the column names
input_data = input_data.drop(index=input_data.index[0])

# Check variable types
print(input_data.dtypes)

# Create 'Cultivar' class labels based on row names (index)
input_data['Cultivar'] = input_data.index

# Replace cultivar labels as in R's sub function
input_data['Cultivar'] = input_data['Cultivar'].replace({
    r'Sul\d{1,}': 'Sultana',
    r'Sug\d{1,5}': 'Sugra-39',
    r'Cur\d{1,5}': 'Currents'
}, regex=True)

# Ensure Cultivar is a categorical (factor-like) column
input_data['Cultivar'] = input_data['Cultivar'].astype('category')

# Check if 'Cultivar' is a factor (categorical column)
print(input_data['Cultivar'].dtype)

# Reset row names (index) to numeric
input_data.reset_index(drop=True, inplace=True)

# Summarize the number of samples by Cultivar
cultivar_summary = input_data['Cultivar'].value_counts()
print(cultivar_summary)

# Split the dataset (2/3 training, 1/3 validation)
train_data, val_data = train_test_split(input_data, test_size=1/3, random_state=17, stratify=input_data['Cultivar'])

# Display dataset sizes
print("Training set size:", train_data.shape)
print("Validation set size:", val_data.shape)

#===============================================================================
# Prepare Data for Training and Testing
#===============================================================================

# Separate features (X) and target variable (y)
X_train = train_data.drop(columns=['Cultivar'])  # Features
y_train = train_data['Cultivar']  # Target variable

X_test = val_data.drop(columns=['Cultivar'])
y_test = val_data['Cultivar']

#===============================================================================
# Train the Model
#===============================================================================

# Initialize and train a Random Forest classifier
model = RandomForestClassifier(n_estimators=100, random_state=17)
model.fit(X_train, y_train)

#===============================================================================
# Test the Model and Generate Accuracy Metrics
#===============================================================================

# Predict on the validation set
y_pred = model.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy:.2f}")

# Generate confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:\n", conf_matrix)

sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Confusion Matrix')
plt.show()

# Compute the Kappa Index
kappa = cohen_kappa_score(y_test, y_pred)
print(f"Kappa Index: {kappa:.4f}")

# Generate classification report
class_report = classification_report(y_test, y_pred)
print("\nClassification Report:\n", class_report)

# Predict probabilities for ROC Curve
y_score = model.predict_proba(X_test)

# Binarize the labels for multi-class ROC
n_classes = len(np.unique(y_test))
y_test_binarized = label_binarize(y_test, classes=np.unique(y_test))

# Compute ROC curve and AUC for each class
plt.figure(figsize=(10, 6))
for i in range(n_classes):
    fpr, tpr, _ = roc_curve(y_test_binarized[:, i], y_score[:, i])
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f'Class {i} (AUC = {roc_auc:.2f})')

plt.plot([0, 1], [0, 1], 'k--')  # Diagonal line for reference
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend(loc='lower right')
plt.show()

#===============================================================================
# Feature Selection Using Random Forest
#===============================================================================
# Load data for feature selection
# Assuming 'input_data' is the processed dataframe
X = input_data.drop(columns=['Cultivar'])  # Features
y = input_data['Cultivar']  # Target variable

# Split the dataset (2/3 training, 1/3 testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3, random_state=17, stratify=y)

# Step 1: Initialize a RandomForestClassifier for Boruta
rf = RandomForestClassifier(n_estimators=100, random_state=17, n_jobs=-1)

# Step 2: Initialize Boruta feature selector
boruta_selector = BorutaPy(rf, n_estimators='auto', random_state=17, verbose=2)

# Step 3: Fit Boruta on training data
boruta_selector.fit(X_train.to_numpy(), y_train.to_numpy())

# Step 4: Select the important features
selected_features = X.columns[boruta_selector.support_]
X_train_selected = X_train[selected_features]
X_test_selected = X_test[selected_features]

print(f"Selected Features ({len(selected_features)}):", list(selected_features))

#===============================================================================
# Train Model on Selected Features
#===============================================================================

# Train a new Random Forest classifier on reduced feature set
model = RandomForestClassifier(n_estimators=100, random_state=17)
model.fit(X_train_selected, y_train)

# Train a new Random Forest classifier with class weights
#model = RandomForestClassifier(n_estimators=100, random_state=17, class_weight='balanced')
#model.fit(X_train_selected, y_train)
#===============================================================================
# Test Model on Validation Data and Generate Accuracy Metrics
#===============================================================================

# Predict on the validation set
y_pred = model.predict(X_test_selected)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"\nModel Accuracy (with feature selection): {accuracy:.2f}")

# Generate confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:\n", conf_matrix)

sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Confusion Matrix')
plt.show()

# Compute the Kappa Index
kappa = cohen_kappa_score(y_test, y_pred)
print(f"Kappa Index: {kappa:.4f}")

# Generate classification report
class_report = classification_report(y_test, y_pred)
print("\nClassification Report:\n", class_report)

# Predict probabilities for ROC Curve
y_score = model.predict_proba(X_test_selected)

# Binarize the labels for multi-class ROC
n_classes = len(np.unique(y_test))
y_test_binarized = label_binarize(y_test, classes=np.unique(y_test))

# Compute ROC curve and AUC for each class
plt.figure(figsize=(10, 6))
for i in range(n_classes):
    fpr, tpr, _ = roc_curve(y_test_binarized[:, i], y_score[:, i])
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f'Class {i} (AUC = {roc_auc:.2f})')

plt.plot([0, 1], [0, 1], 'k--')  # Diagonal line for reference
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend(loc='lower right')
plt.show()

#==============================================================================
#Balancing class distribution before classification
#==============================================================================
# Check class distribution before balancing
print("Class distribution before balancing:\n", y_train.value_counts())

# Apply SMOTE to balance the training dataset
smote = SMOTE(random_state=17)
X_train_balanced, y_train_balanced = smote.fit_resample(X_train, y_train)

# Check class distribution after balancing
print("Class distribution after balancing:\n", y_train_balanced.value_counts())

# Train a new model on the balanced dataset
balanced_model = RandomForestClassifier(n_estimators=100, random_state=17)
balanced_model.fit(X_train_balanced, y_train_balanced)

# Predict on the test set (test set remains unchanged)
y_pred = balanced_model.predict(X_test)

# Evaluate performance
accuracy = accuracy_score(y_test, y_pred)
print(f"\nModel Accuracy (after balancing): {accuracy:.2f}")

conf_matrix = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:\n", conf_matrix)

sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Confusion Matrix')
plt.show()

# Compute the Kappa Index
kappa = cohen_kappa_score(y_test, y_pred)
print(f"Kappa Index: {kappa:.4f}")

class_report = classification_report(y_test, y_pred)
print("\nClassification Report:\n", class_report)

# Predict probabilities for ROC Curve
y_score = balanced_model.predict_proba(X_test)

# Binarize the labels for multi-class ROC
n_classes = len(np.unique(y_test))
y_test_binarized = label_binarize(y_test, classes=np.unique(y_test))

# Compute ROC curve and AUC for each class
plt.figure(figsize=(10, 6))
for i in range(n_classes):
    fpr, tpr, _ = roc_curve(y_test_binarized[:, i], y_score[:, i])
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f'Class {i} (AUC = {roc_auc:.2f})')

plt.plot([0, 1], [0, 1], 'k--')  # Diagonal line for reference
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend(loc='lower right')
plt.show()

#===============================================================================
# Prepare Data for Training and Testing using XGBoost
#===============================================================================

# Separate features (X) and target variable (y)
X_train = train_data.drop(columns=['Cultivar'])  # Features
y_train = train_data['Cultivar']  # Target variable

X_test = val_data.drop(columns=['Cultivar'])
y_test = val_data['Cultivar']

# Create a LabelEncoder object
label_encoder = LabelEncoder()

# Fit the encoder to the training target variable and transform it
y_train_encoded = label_encoder.fit_transform(y_train)

# Transform the test target variable using the trained encoder
y_test_encoded = label_encoder.transform(y_test)
#===============================================================================
# Train the Model Using XGBoost
#===============================================================================

# Initialize and train an XGBoost classifier
xgb_model = XGBClassifier(n_estimators=100, random_state=17, use_label_encoder=False, eval_metric='mlogloss')
xgb_model.fit(X_train, y_train_encoded)

#===============================================================================
# Test the Model and Generate Accuracy Metrics
#===============================================================================

# Predict on the validation set
y_pred_encoded = xgb_model.predict(X_test)

# Decode the predicted labels back to original string labels
y_pred = label_encoder.inverse_transform(y_pred_encoded)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"XGBoost Model Accuracy: {accuracy:.2f}")

# Generate confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:\n", conf_matrix)

sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Confusion Matrix')
plt.show()

# Compute the Kappa Index
kappa = cohen_kappa_score(y_test, y_pred)
print(f"Kappa Index: {kappa:.4f}")

# Generate classification report
class_report = classification_report(y_test, y_pred)
print("\nClassification Report:\n", class_report)

# Predict probabilities for ROC Curve
y_score = xgb_model.predict_proba(X_test)

# Binarize the labels for multi-class ROC
n_classes = len(np.unique(y_test))
y_test_binarized = label_binarize(y_test, classes=np.unique(y_test))

# Compute ROC curve and AUC for each class
plt.figure(figsize=(10, 6))
for i in range(n_classes):
    fpr, tpr, _ = roc_curve(y_test_binarized[:, i], y_score[:, i])
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f'Class {i} (AUC = {roc_auc:.2f})')

plt.plot([0, 1], [0, 1], 'k--')  # Diagonal line for reference
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend(loc='lower right')
plt.show()

#===============================================================================
# Handle Class Imbalance Using SMOTE
#===============================================================================

# Initialize SMOTE (Synthetic Minority Over-sampling Technique)
smote = SMOTE(random_state=17)

# Apply SMOTE only to training data
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train_encoded)

# Check the new class distribution
unique, counts = np.unique(y_train_resampled, return_counts=True)
print("\nClass distribution after SMOTE:")
for u, c in zip(unique, counts):
    print(f"Class {label_encoder.inverse_transform([u])[0]}: {c} samples")

#===============================================================================
# Train the Model Using XGBoost
#===============================================================================

# Initialize and train an XGBoost classifier
xgb_model = XGBClassifier(n_estimators=100, random_state=17, use_label_encoder=False, eval_metric='mlogloss')
xgb_model.fit(X_train_resampled, y_train_resampled)

#===============================================================================
# Test the Model and Generate Accuracy Metrics
#===============================================================================

# Predict on the validation set
y_pred_encoded = xgb_model.predict(X_test)

# Decode the predicted labels back to original string labels
y_pred = label_encoder.inverse_transform(y_pred_encoded)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"\nXGBoost Model Accuracy (with class balancing): {accuracy:.2f}")

# Generate confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:\n", conf_matrix)

sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Confusion matrix')
plt.show()

# Compute the Kappa Index
kappa = cohen_kappa_score(y_test, y_pred)
print(f"Kappa Index: {kappa:.4f}")

# Generate classification report
class_report = classification_report(y_test, y_pred)
print("\nClassification Report:\n", class_report)

# Predict probabilities for ROC Curve
y_score = xgb_model.predict_proba(X_test)

# Binarize the labels for multi-class ROC
n_classes = len(np.unique(y_test))
y_test_binarized = label_binarize(y_test, classes=np.unique(y_test))

# Compute ROC curve and AUC for each class
plt.figure(figsize=(10, 6))
for i in range(n_classes):
    fpr, tpr, _ = roc_curve(y_test_binarized[:, i], y_score[:, i])
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f'Class {i} (AUC = {roc_auc:.2f})')

plt.plot([0, 1], [0, 1], 'k--')  # Diagonal line for reference
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend(loc='lower right')
plt.show()

#===============================================================================
# Feature Selection Using XGBoost Feature Importance
#===============================================================================
# Train an initial XGBoost model for Boruta feature selection
feature_selection_model = XGBClassifier(n_estimators=100, random_state=17, use_label_encoder=False, eval_metric='mlogloss')
feature_selection_model.fit(X_train_resampled, y_train_resampled)

# Initialize Boruta feature selector
boruta_selector = BorutaPy(feature_selection_model, n_estimators='auto', random_state=17, verbose=2)

# Fit Boruta on the training data
boruta_selector.fit(X_train_resampled, y_train_resampled)

# Select important features
selected_features = X_train_resampled.columns[boruta_selector.support_]
X_train_selected = X_train_resampled[selected_features]
X_test_selected = X_test[selected_features]

print(f"\nSelected Features ({len(selected_features)}):", list(selected_features))
#===============================================================================
# Train the Model Using Selected Features
#===============================================================================

# Initialize and train an XGBoost classifier on selected features
xgb_model_selected = XGBClassifier(n_estimators=100, random_state=17, use_label_encoder=False, eval_metric='mlogloss')
xgb_model_selected.fit(X_train_selected, y_train_resampled)

#===============================================================================
# Test the Model and Generate Accuracy Metrics
#===============================================================================

# Predict on the validation set
y_pred_selected_encoded = xgb_model_selected.predict(X_test_selected)

# Decode the predicted labels back to original string labels
y_pred_selected = label_encoder.inverse_transform(y_pred_selected_encoded)

# Calculate accuracy
accuracy_selected = accuracy_score(y_test, y_pred_selected)
print(f"\nXGBoost Model Accuracy (with feature selection): {accuracy_selected:.2f}")

# Generate confusion matrix
conf_matrix_selected = confusion_matrix(y_test, y_pred_selected)
print("\nConfusion Matrix:\n", conf_matrix_selected)

sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Confusion matrix')
plt.show()

# Compute the Kappa Index
kappa = cohen_kappa_score(y_test, y_pred)
print(f"Kappa Index: {kappa:.4f}")

# Generate classification report
class_report_selected = classification_report(y_test, y_pred_selected)
print("\nClassification Report:\n", class_report_selected)

# Predict probabilities for ROC Curve
y_score = xgb_model_selected.predict_proba(X_test_selected)

# Binarize the labels for multi-class ROC
n_classes = len(np.unique(y_test))
y_test_binarized = label_binarize(y_test, classes=np.unique(y_test))

# Compute ROC curve and AUC for each class
plt.figure(figsize=(10, 6))
for i in range(n_classes):
    fpr, tpr, _ = roc_curve(y_test_binarized[:, i], y_score[:, i])
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f'Class {i} (AUC = {roc_auc:.2f})')

plt.plot([0, 1], [0, 1], 'k--')  # Diagonal line for reference
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend(loc='lower right')
plt.show()

!pip install boruta

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from boruta import BorutaPy
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.decomposition import PCA
from sklearn.feature_selection import SelectFromModel
from sklearn.preprocessing import label_binarize
from sklearn.metrics import roc_curve, auc
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score, classification_report, precision_recall_curve
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from imblearn.over_sampling import SMOTE
import xgboost as xgb
from xgboost import XGBClassifier
from sklearn.preprocessing import LabelEncoder

#===============================================================================
# Load Spectral Data
#===============================================================================
# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Define the Google Drive path to the rawASD data (adjust the file path as needed)
file_path = ('/content/drive/MyDrive/Spectral samples/ASD_raw_Dec2023_CA.csv')

#  Load the rawASD dataset
rawASD = pd.read_csv(file_path)

# Remove noisy wavebands
noisy_bands = list(range(350, 400)) + list(range(1350, 1426)) + list(range(1825, 1926)) + list(range(2451, 2501))
rawASD = rawASD[~rawASD.iloc[:, 0].isin(noisy_bands)]

# Check the first few rows of the dataset to ensure it loaded correctly
print(rawASD.head())
print("Dataset dimensions: ", rawASD.shape)

#===============================================================================
# Plot All Spectra with Atmospheric Windows
#===============================================================================

# Plot all spectra (excluding first column which contains wavelength)
plt.figure(figsize=(10, 6))
for col in rawASD.columns[1:]:
    plt.plot(rawASD.iloc[:, 0], rawASD[col], linewidth=1)

plt.xlabel('Wavelength (nm)')
plt.ylabel('Sample Reflectance')
plt.title('Spectral Plot')
plt.show()

#===============================================================================
# Clean and Reformat Data for Analysis
#===============================================================================
# Convert the rawASD DataFrame (transposed)
input_data = rawASD.T # Transpose the DataFrame
input_data.columns = rawASD.iloc[:, 0]  # Set column names to first row
input_data.columns = ['wb_' + str(col) if isinstance(col, (int, float)) else 'wb_' + col for col in input_data.columns]

# Remove the first row (header) which is now the column names
input_data = input_data.drop(index=input_data.index[0])

# Check variable types
print(input_data.dtypes)

# Create 'Cultivar' class labels based on row names (index)
input_data['Cultivar'] = input_data.index

# Replace cultivar labels as in R's sub function
input_data['Cultivar'] = input_data['Cultivar'].replace({
    r'Sul\d{1,}': 'Sultana',
    r'Sug\d{1,5}': 'Sugra-39',
    r'Cur\d{1,5}': 'Currents'
}, regex=True)

# Ensure Cultivar is a categorical (factor-like) column
input_data['Cultivar'] = input_data['Cultivar'].astype('category')

# Check if 'Cultivar' is a factor (categorical column)
print(input_data['Cultivar'].dtype)

# Reset row names (index) to numeric
input_data.reset_index(drop=True, inplace=True)

# Summarize the number of samples by Cultivar
cultivar_summary = input_data['Cultivar'].value_counts()
print(cultivar_summary)

# Split the dataset (2/3 training, 1/3 validation)
train_data, val_data = train_test_split(input_data, test_size=1/3, random_state=17, stratify=input_data['Cultivar'])

# Display dataset sizes
print("Training set size:", train_data.shape)
print("Validation set size:", val_data.shape)

#===============================================================================
# Prepare Data for Training and Testing
#===============================================================================

# Separate features (X) and target variable (y)
X_train = train_data.drop(columns=['Cultivar'])  # Features
y_train = train_data['Cultivar']  # Target variable

X_test = val_data.drop(columns=['Cultivar'])
y_test = val_data['Cultivar']

#===============================================================================
# Train the Model
#===============================================================================

# Initialize and train a Random Forest classifier
model = RandomForestClassifier(n_estimators=100, random_state=17)
model.fit(X_train, y_train)

#===============================================================================
# Test the Model and Generate Accuracy Metrics
#===============================================================================

# Predict on the validation set
y_pred = model.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy:.2f}")

# Generate confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:\n", conf_matrix)

sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Confusion Matrix')
plt.show()

# Compute the Kappa Index
kappa = cohen_kappa_score(y_test, y_pred)
print(f"Kappa Index: {kappa:.4f}")

# Generate classification report
class_report = classification_report(y_test, y_pred)
print("\nClassification Report:\n", class_report)

# Predict probabilities for ROC Curve
y_score = model.predict_proba(X_test)

# Binarize the labels for multi-class ROC
n_classes = len(np.unique(y_test))
y_test_binarized = label_binarize(y_test, classes=np.unique(y_test))

# Compute ROC curve and AUC for each class
plt.figure(figsize=(10, 6))
for i in range(n_classes):
    fpr, tpr, _ = roc_curve(y_test_binarized[:, i], y_score[:, i])
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f'Class {i} (AUC = {roc_auc:.2f})')

plt.plot([0, 1], [0, 1], 'k--')  # Diagonal line for reference
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend(loc='lower right')
plt.show()

#===============================================================================
# Feature Selection Using Random Forest
#===============================================================================
# Load data for feature selection
# Assuming 'input_data' is the processed dataframe
X = input_data.drop(columns=['Cultivar'])  # Features
y = input_data['Cultivar']  # Target variable

# Split the dataset (2/3 training, 1/3 testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3, random_state=17, stratify=y)

# Step 1: Initialize a RandomForestClassifier for Boruta
rf = RandomForestClassifier(n_estimators=100, random_state=17, n_jobs=-1)

# Step 2: Initialize Boruta feature selector
boruta_selector = BorutaPy(rf, n_estimators='auto', random_state=17, verbose=2)

# Step 3: Fit Boruta on training data
boruta_selector.fit(X_train.to_numpy(), y_train.to_numpy())

# Step 4: Select the important features
selected_features = X.columns[boruta_selector.support_]
X_train_selected = X_train[selected_features]
X_test_selected = X_test[selected_features]

print(f"Selected Features ({len(selected_features)}):", list(selected_features))

#===============================================================================
# Train Model on Selected Features
#===============================================================================

# Train a new Random Forest classifier on reduced feature set
model = RandomForestClassifier(n_estimators=100, random_state=17)
model.fit(X_train_selected, y_train)

# Train a new Random Forest classifier with class weights
#model = RandomForestClassifier(n_estimators=100, random_state=17, class_weight='balanced')
#model.fit(X_train_selected, y_train)
#===============================================================================
# Test Model on Validation Data and Generate Accuracy Metrics
#===============================================================================

# Predict on the validation set
y_pred = model.predict(X_test_selected)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"\nModel Accuracy (with feature selection): {accuracy:.2f}")

# Generate confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:\n", conf_matrix)

sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Confusion Matrix')
plt.show()

# Compute the Kappa Index
kappa = cohen_kappa_score(y_test, y_pred)
print(f"Kappa Index: {kappa:.4f}")

# Generate classification report
class_report = classification_report(y_test, y_pred)
print("\nClassification Report:\n", class_report)

# Predict probabilities for ROC Curve
y_score = model.predict_proba(X_test_selected)

# Binarize the labels for multi-class ROC
n_classes = len(np.unique(y_test))
y_test_binarized = label_binarize(y_test, classes=np.unique(y_test))

# Compute ROC curve and AUC for each class
plt.figure(figsize=(10, 6))
for i in range(n_classes):
    fpr, tpr, _ = roc_curve(y_test_binarized[:, i], y_score[:, i])
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f'Class {i} (AUC = {roc_auc:.2f})')

plt.plot([0, 1], [0, 1], 'k--')  # Diagonal line for reference
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend(loc='lower right')
plt.show()

#==============================================================================
#Balancing class distribution before classification
#==============================================================================
# Check class distribution before balancing
print("Class distribution before balancing:\n", y_train.value_counts())

# Apply SMOTE to balance the training dataset
smote = SMOTE(random_state=17)
X_train_balanced, y_train_balanced = smote.fit_resample(X_train, y_train)

# Check class distribution after balancing
print("Class distribution after balancing:\n", y_train_balanced.value_counts())

# Train a new model on the balanced dataset
balanced_model = RandomForestClassifier(n_estimators=100, random_state=17)
balanced_model.fit(X_train_balanced, y_train_balanced)

# Predict on the test set (test set remains unchanged)
y_pred = balanced_model.predict(X_test)

# Evaluate performance
accuracy = accuracy_score(y_test, y_pred)
print(f"\nModel Accuracy (after balancing): {accuracy:.2f}")

conf_matrix = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:\n", conf_matrix)

sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Confusion Matrix')
plt.show()

# Compute the Kappa Index
kappa = cohen_kappa_score(y_test, y_pred)
print(f"Kappa Index: {kappa:.4f}")

class_report = classification_report(y_test, y_pred)
print("\nClassification Report:\n", class_report)

# Predict probabilities for ROC Curve
y_score = balanced_model.predict_proba(X_test)

# Binarize the labels for multi-class ROC
n_classes = len(np.unique(y_test))
y_test_binarized = label_binarize(y_test, classes=np.unique(y_test))

# Compute ROC curve and AUC for each class
plt.figure(figsize=(10, 6))
for i in range(n_classes):
    fpr, tpr, _ = roc_curve(y_test_binarized[:, i], y_score[:, i])
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f'Class {i} (AUC = {roc_auc:.2f})')

plt.plot([0, 1], [0, 1], 'k--')  # Diagonal line for reference
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend(loc='lower right')
plt.show()

#===============================================================================
# Prepare Data for Training and Testing using XGBoost
#===============================================================================

# Separate features (X) and target variable (y)
X_train = train_data.drop(columns=['Cultivar'])  # Features
y_train = train_data['Cultivar']  # Target variable

X_test = val_data.drop(columns=['Cultivar'])
y_test = val_data['Cultivar']

# Create a LabelEncoder object
label_encoder = LabelEncoder()

# Fit the encoder to the training target variable and transform it
y_train_encoded = label_encoder.fit_transform(y_train)

# Transform the test target variable using the trained encoder
y_test_encoded = label_encoder.transform(y_test)
#===============================================================================
# Train the Model Using XGBoost
#===============================================================================

# Initialize and train an XGBoost classifier
xgb_model = XGBClassifier(n_estimators=100, random_state=17, use_label_encoder=False, eval_metric='mlogloss')
xgb_model.fit(X_train, y_train_encoded)

#===============================================================================
# Test the Model and Generate Accuracy Metrics
#===============================================================================

# Predict on the validation set
y_pred_encoded = xgb_model.predict(X_test)

# Decode the predicted labels back to original string labels
y_pred = label_encoder.inverse_transform(y_pred_encoded)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"XGBoost Model Accuracy: {accuracy:.2f}")

# Generate confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:\n", conf_matrix)

sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Confusion Matrix')
plt.show()

# Compute the Kappa Index
kappa = cohen_kappa_score(y_test, y_pred)
print(f"Kappa Index: {kappa:.4f}")

# Generate classification report
class_report = classification_report(y_test, y_pred)
print("\nClassification Report:\n", class_report)

# Predict probabilities for ROC Curve
y_score = xgb_model.predict_proba(X_test)

# Binarize the labels for multi-class ROC
n_classes = len(np.unique(y_test))
y_test_binarized = label_binarize(y_test, classes=np.unique(y_test))

# Compute ROC curve and AUC for each class
plt.figure(figsize=(10, 6))
for i in range(n_classes):
    fpr, tpr, _ = roc_curve(y_test_binarized[:, i], y_score[:, i])
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f'Class {i} (AUC = {roc_auc:.2f})')

plt.plot([0, 1], [0, 1], 'k--')  # Diagonal line for reference
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend(loc='lower right')
plt.show()

#===============================================================================
# Handle Class Imbalance Using SMOTE
#===============================================================================

# Initialize SMOTE (Synthetic Minority Over-sampling Technique)
smote = SMOTE(random_state=17)

# Apply SMOTE only to training data
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train_encoded)

# Check the new class distribution
unique, counts = np.unique(y_train_resampled, return_counts=True)
print("\nClass distribution after SMOTE:")
for u, c in zip(unique, counts):
    print(f"Class {label_encoder.inverse_transform([u])[0]}: {c} samples")

#===============================================================================
# Train the Model Using XGBoost
#===============================================================================

# Initialize and train an XGBoost classifier
xgb_model = XGBClassifier(n_estimators=100, random_state=17, use_label_encoder=False, eval_metric='mlogloss')
xgb_model.fit(X_train_resampled, y_train_resampled)

#===============================================================================
# Test the Model and Generate Accuracy Metrics
#===============================================================================

# Predict on the validation set
y_pred_encoded = xgb_model.predict(X_test)

# Decode the predicted labels back to original string labels
y_pred = label_encoder.inverse_transform(y_pred_encoded)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"\nXGBoost Model Accuracy (with class balancing): {accuracy:.2f}")

# Generate confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:\n", conf_matrix)

sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Confusion matrix')
plt.show()

# Compute the Kappa Index
kappa = cohen_kappa_score(y_test, y_pred)
print(f"Kappa Index: {kappa:.4f}")

# Generate classification report
class_report = classification_report(y_test, y_pred)
print("\nClassification Report:\n", class_report)

# Predict probabilities for ROC Curve
y_score = xgb_model.predict_proba(X_test)

# Binarize the labels for multi-class ROC
n_classes = len(np.unique(y_test))
y_test_binarized = label_binarize(y_test, classes=np.unique(y_test))

# Compute ROC curve and AUC for each class
plt.figure(figsize=(10, 6))
for i in range(n_classes):
    fpr, tpr, _ = roc_curve(y_test_binarized[:, i], y_score[:, i])
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f'Class {i} (AUC = {roc_auc:.2f})')

plt.plot([0, 1], [0, 1], 'k--')  # Diagonal line for reference
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend(loc='lower right')
plt.show()

#===============================================================================
# Feature Selection Using XGBoost Feature Importance
#===============================================================================
# Train an initial XGBoost model for Boruta feature selection
feature_selection_model = XGBClassifier(n_estimators=100, random_state=17, use_label_encoder=False, eval_metric='mlogloss')
feature_selection_model.fit(X_train_resampled, y_train_resampled)

# Initialize Boruta feature selector
boruta_selector = BorutaPy(feature_selection_model, n_estimators='auto', random_state=17, verbose=2)

# Fit Boruta on the training data
boruta_selector.fit(X_train_resampled, y_train_resampled)

# Select important features
selected_features = X_train_resampled.columns[boruta_selector.support_]
X_train_selected = X_train_resampled[selected_features]
X_test_selected = X_test[selected_features]

print(f"\nSelected Features ({len(selected_features)}):", list(selected_features))
#===============================================================================
# Train the Model Using Selected Features
#===============================================================================

# Initialize and train an XGBoost classifier on selected features
xgb_model_selected = XGBClassifier(n_estimators=100, random_state=17, use_label_encoder=False, eval_metric='mlogloss')
xgb_model_selected.fit(X_train_selected, y_train_resampled)

#===============================================================================
# Test the Model and Generate Accuracy Metrics
#===============================================================================

# Predict on the validation set
y_pred_selected_encoded = xgb_model_selected.predict(X_test_selected)

# Decode the predicted labels back to original string labels
y_pred_selected = label_encoder.inverse_transform(y_pred_selected_encoded)

# Calculate accuracy
accuracy_selected = accuracy_score(y_test, y_pred_selected)
print(f"\nXGBoost Model Accuracy (with feature selection): {accuracy_selected:.2f}")

# Generate confusion matrix
conf_matrix_selected = confusion_matrix(y_test, y_pred_selected)
print("\nConfusion Matrix:\n", conf_matrix_selected)

sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Confusion matrix')
plt.show()

# Compute the Kappa Index
kappa = cohen_kappa_score(y_test, y_pred)
print(f"Kappa Index: {kappa:.4f}")

# Generate classification report
class_report_selected = classification_report(y_test, y_pred_selected)
print("\nClassification Report:\n", class_report_selected)

# Predict probabilities for ROC Curve
y_score = xgb_model_selected.predict_proba(X_test_selected)

# Binarize the labels for multi-class ROC
n_classes = len(np.unique(y_test))
y_test_binarized = label_binarize(y_test, classes=np.unique(y_test))

# Compute ROC curve and AUC for each class
plt.figure(figsize=(10, 6))
for i in range(n_classes):
    fpr, tpr, _ = roc_curve(y_test_binarized[:, i], y_score[:, i])
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f'Class {i} (AUC = {roc_auc:.2f})')

plt.plot([0, 1], [0, 1], 'k--')  # Diagonal line for reference
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend(loc='lower right')
plt.show()